TARGET = libminibae-$(WTVLIB_FILE_SUFFIX).a

vpath %.c $(CURDIR)/external/heyigor/miniBAE/minibae/BAE_Source/Common $(CURDIR)/external/heyigor/miniBAE/minibae/BAE_Source/Platform 
vpath %.c $(CURDIR)/external/heyigor/miniBAE/minibae/banks/patches
vpath %.c $(CURDIR)/external/heyigor/miniBAE/minibae/BAE_MPEG_Source_II

MINIBAE_INC := -I$(CURDIR)/external/heyigor/miniBAE/minibae/BAE_Source/Common
MINIBAE_INC += -I$(CURDIR)/external/heyigor/miniBAE/minibae/BAE_Source/Platform
MINIBAE_INC += -I$(CURDIR)/external/heyigor/miniBAE/minibae/BAE_MPEG_Source_II
MINIBAE_INC += -I$(CURDIR)/external/heyigor/miniBAE/minibae/banks/patches

SRC := 

SRC += \
	DriverTools.c \
	GenAudioStreams.c \
	GenCache.c \
	GenChorus.c \
	GenFiltersReverbU3232.c \
	GenInterp2ReverbU3232.c \
	GenOutput.c \
	GenPatch.c \
	GenReverb.c \
	GenReverbNew.c \
	GenSample.c \
	GenSeq.c \
	GenSeqTools.c \
	GenSetup.c \
	GenSong.c \
	GenSoundFiles.c \
	GenSynth.c \
	GenSynthFiltersSimple.c \
	GenSynthFiltersU3232.c \
	GenSynthInterp2Simple.c \
	GenSynthInterp2U3232.c \
	MiniBAE.c \
	NewNewLZSS.c \
	SampleTools.c \
	X_API.c \
	X_Decompress.c \
	X_IMA.c \
	g711.c \
	g721.c \
	g723_24.c \
	g723_40.c \
	g72x.c \
	BAEPatches.c

OBJ_DIR := $(CURDIR)/external/heyigor/miniBAE/minibae/obj/
OBJ := $(addprefix $(OBJ_DIR),$(addsuffix .o,$(basename ${SRC})))

MINIBAE_CFLAGS   := $(WTV_CFLAGS) $(MINIBAE_INC)
MINIBAE_CXXFLAGS := $(WTV_CXXFLAGS) $(MINIBAE_INC)

$(TARGET): $(OBJ)
	$(AR) rcs $(TARGET) $(OBJ)

# Rules for compiling source files to object files
$(OBJ_DIR)%.o : %.cpp
	@echo "    [CC BAE-$(WTVLIB_FILE_SUFFIX)] $<"
	@mkdir -p $(OBJ_DIR)
	@${CXX} -c ${MINIBAE_CXXFLAGS} $< -o $@

$(OBJ_DIR)%.o : %.c
	@echo "    [CXX BAE-$(WTVLIB_FILE_SUFFIX)] $<"
	@mkdir -p $(OBJ_DIR)
	@${CC} -c ${MINIBAE_CFLAGS} $< -o $@

install-minibae:
	mkdir -p $(INSTALL_DIR)/lib
	install -Cv -m 0644 libminibae-$(WTVLIB_FILE_SUFFIX).a $(INSTALL_DIR)/lib/libminibae-$(WTVLIB_FILE_SUFFIX).a
	mkdir -p $(INSTALL_DIR)/include/audio/minibae
	install -Cv -m 0644 $(CURDIR)/external/heyigor/miniBAE/minibae/BAE_Source/Common/g72x.h $(INSTALL_DIR)/include/audio/minibae/g72x.h
	install -Cv -m 0644 $(CURDIR)/external/heyigor/miniBAE/minibae/BAE_Source/Common/GenCache.h $(INSTALL_DIR)/include/audio/minibae/GenCache.h
	install -Cv -m 0644 $(CURDIR)/external/heyigor/miniBAE/minibae/BAE_Source/Common/GenPriv.h $(INSTALL_DIR)/include/audio/minibae/GenPriv.h
	install -Cv -m 0644 $(CURDIR)/external/heyigor/miniBAE/minibae/BAE_Source/Common/GenSeqTools.h $(INSTALL_DIR)/include/audio/minibae/GenSeqTools.h
	install -Cv -m 0644 $(CURDIR)/external/heyigor/miniBAE/minibae/BAE_Source/Common/GenSnd.h $(INSTALL_DIR)/include/audio/minibae/GenSnd.h
	install -Cv -m 0644 $(CURDIR)/external/heyigor/miniBAE/minibae/BAE_Source/Common/MiniBAE.h $(INSTALL_DIR)/include/audio/minibae/MiniBAE.h
	install -Cv -m 0644 $(CURDIR)/external/heyigor/miniBAE/minibae/BAE_Source/Common/X_API.h $(INSTALL_DIR)/include/audio/minibae/X_API.h
	install -Cv -m 0644 $(CURDIR)/external/heyigor/miniBAE/minibae/BAE_Source/Common/X_Assert.h $(INSTALL_DIR)/include/audio/minibae/X_Assert.h
	install -Cv -m 0644 $(CURDIR)/external/heyigor/miniBAE/minibae/BAE_Source/Common/X_Formats.h $(INSTALL_DIR)/include/audio/minibae/X_Formats.h
	install -Cv -m 0644 $(CURDIR)/external/heyigor/miniBAE/minibae/BAE_Source/Common/X_PackStructures.h $(INSTALL_DIR)/include/audio/minibae/X_PackStructures.h
	install -Cv -m 0644 $(CURDIR)/external/heyigor/miniBAE/minibae/BAE_Source/Common/X_UnpackStructures.h $(INSTALL_DIR)/include/audio/minibae/X_UnpackStructures.h
	install -Cv -m 0644 $(CURDIR)/external/heyigor/miniBAE/minibae/BAE_MPEG_Source_II/XMPEG_BAE_API.h $(INSTALL_DIR)/include/audio/minibae/XMPEG_BAE_API.h
	install -Cv -m 0644 $(CURDIR)/external/heyigor/miniBAE/minibae/BAE_Source/Platform/BAE_API.h $(INSTALL_DIR)/include/audio/minibae/BAE_API.h
	install -Cv -m 0644 $(CURDIR)/external/heyigor/miniBAE/minibae/BAE_Source/Platform/BAEBuildOptions_libwtv.h $(INSTALL_DIR)/include/audio/minibae/BAEBuildOptions_libwtv.h

clean-minibae:
	@rm -f $(TARGET)
	@rm -rdf $(OBJ_DIR)
	@rm -rdf $(CURDIR)/external/heyigor/miniBAE/minibae/build
	@echo libminibae cleaned!
